### ISSUE TITLE
alloca.h is not standard

### ISSUE THREAD

**Issue by aameen951** [Chronister/twc#5]
../code/twitter.c(5): fatal error C1083: Cannot open include file: 'alloca.h': No such file or directory

**Comment by chr-1x** [comment]
I'm aware it's nonstandard, but what compiler + version is this?

**Comment by aameen951** [comment]
Im using MSVC 2015

**Comment by chr-1x** [comment]
Ah, this must be due to the change I just pushed. Seems MSVC and GCC/Clang provide it in different headers. I'll add a guard to check compiler version there. At the moment alloca is used several places where I don't have good alternatives that fit within my API constraints, so it's necessary to keep around.

**Comment by aameen951** [comment]
in MSVC it is already included in malloc.h [_alloca](https://msdn.microsoft.com/en-us/library/wb1s57t5.aspx)

you can wrap the include with ifndef _MSC_VER

**Comment by chr-1x** [comment]
This is done and committed. Thanks for the feedback!
